version: "3.7"

services:
  nodered:
    image: nodered/node-red:latest
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./dist:/data/nodes

volumes:
  node-red-data:

networks:
  node-red-net:
